pipeline {
    agent {
        kubernetes {
            inheritFrom 'docker-image-pod'
            defaultContainer 'buildkit'
            yaml """
                apiVersion: v1
                kind: Pod
                metadata:
                  label:
                    jenkins: docker-image-pod
                spec:
                  containers:
                    - name: buildkit
                      image: moby/buildkit:master
                      tty: true
                      securityContext:
                        privileged: true
                      volumeMounts:
                        - name: docker-config
                          mountPath: '/root/.docker'
                  volumes:
                    - name: docker-config
                      secret:
                        secretName: 'docker-config'
                  restartPolicy: Never
            """
        }
    }

    parameters {
      string(
        name: 'registry',
        defaultValue: 'registry.example.com:5000',
        description: 'Container Registry'
      )
      string(
        name: 'image_name',
        defaultValue: 'custom-airflow',
        description: 'Image Name'
      )
      string(
        name: 'airflow_version',
        defaultValue: '2.7.2',
        description: 'Apache Airflow version'
      )
    }
    
    stages {
        stage('Build & push image') {
            steps {
                container('buildkit') {
                    sh """
                        buildctl build --frontend dockerfile.v0 --local context=. --no-cache --opt build-arg:AIRFLOW_VERSION=${params.airflow_version} --local dockerfile=. --output type=image,\\"name=${params.registry}/${params.image_name}:${params.airflow_version},${params.registry}/${params.image_name}:latest\\",push=true
                    """
                 }
            }
        }
    }
}


